# Generated by Django 4.0.10 on 2024-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.CharField(default='india', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
